Finder/Finder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from apps.users import views as user_views

app_name = 'finder'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('jobs/', include('apps.jobs.urls')),
    path('materials/', include('apps.materials.urls')),
    path('chat/', include('apps.chat.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('notifications/', include('apps.notifications.urls')),
    path('carrito/', include('apps.carrito.urls')),
    path('venta/', include('apps.venta.urls')),

    path('login/', user_views.login_view, name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('register/', user_views.register_view, name='register'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]
urlpatterns += static( 'media/', document_root  = settings.MEDIA_ROOT )
urlpatterns += static( 'static/', document_root = settings.STATIC_ROOT )

Finder/apps/carrito/urls.py
# apps/materials/urls.py
from django.urls import path
from . import views

app_name = 'carrito'

urlpatterns = [
    path('ver_carrito', views.ver_carrito, name='ver_carrito'),
    path('agregar_carrito/<int:id>/', views.agregar_carrito, name='agregar_carrito'),
    path('incrementar_cantidad_producto_carrito/<int:id>/', views.incrementar_cantidad_producto_carrito, name='incrementar_cantidad_producto_carrito'),
    path('decrementar_cantidad_producto_carrito/<int:id>/', views.decrementar_cantidad_producto_carrito, name='decrementar_cantidad_producto_carrito'),
    path('eliminar_producto_carrito/<int:id>/', views.eliminar_producto_carrito, name='eliminar_producto_carrito'),
]

Finder/apps/users/urls.py
# apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('client_home/', views.client_home, name='client_home'),
    path('worker_home/', views.worker_home, name='worker_home'),
    path('empresa_home/', views.empresa_home, name='empresa_home'),
    path('edit_profile/', views.edit_profile_view, name='edit_profile'),
    path('list_services/', views.list_services, name='list_services'),
    path('create_service/', views.create_service, name='create_service'),
    path('edit_service/<int:pk>/', views.edit_service, name='edit_service'),
    path('delete_service/<int:pk>/', views.delete_service, name='delete_service'),
    path('search_services/', views.search_services, name='search_services'),
    path('ver_perfil/<int:pk>/', views.ver_perfil, name='ver_perfil'),

]

Finder/apps/venta/urls.py
# apps/materials/urls.py
from django.urls import path
from . import views

app_name = 'venta'

urlpatterns = [
    path('realizar_compra/', views.realizar_compra, name='realizar_compra'),
    path('compra/exitosa/', views.compra_exitosa, name='compra_exitosa'),
    path('compras_lista/', views.compras_lista, name='compras_lista'),
    path('ventas_list/', views.ventas_list, name='ventas_list'),
]

Finder/apps/venta/models.py
from django.db import models
from apps.venta.models import *
from django.contrib.auth.models import User
from apps.materials.models import *

# Modelo para el ítem de Venta
class ItemVenta(models.Model):
    producto = models.ForeignKey(Material, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits=6, decimal_places=2)  # Precio al momento de la venta

    def __str__(self):
        return f"{self.producto.nombre} x{self.cantidad}"
    
    class Meta:
        verbose_name = "item_venta"
        verbose_name_plural = "items_ventas"
        ordering=['cantidad']

# Modelo para Venta
class Venta(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ventas')
    items = models.ManyToManyField(ItemVenta)
    fecha_venta = models.DateTimeField(auto_now_add=True)

    def total_venta(self):
        return sum(item.cantidad * item.precio for item in self.items.all())

    def __str__(self):
        return f"Venta {self.id} a {self.usuario.username}"

Finder/apps/venta/views.py
from django.shortcuts import render, redirect
from .models import Venta, ItemVenta
from django.utils import timezone
from apps.carrito.models import ItemCarrito

def realizar_compra(request):
    items_carrito = ItemCarrito.objects.filter(usuario=request.user)
    venta = Venta.objects.create(usuario=request.user, fecha_venta=timezone.now())
    for item in items_carrito:
        item_venta = ItemVenta.objects.create(
            producto=item.producto, 
            cantidad=item.cantidad, 
            precio=item.producto.price
        )
        venta.items.add(item_venta)
        item.producto.save()
        item.delete()
    return redirect('venta:compra_exitosa')
    
def compra_exitosa(request):
    return render(request, 'venta/compra_exitosa.html')

def ventas_list(request):
    ventas = Venta.objects.filter(items__producto__empresa=request.user).distinct().prefetch_related('items')
    return render(request, 'venta/ventas_list.html', {'ventas': ventas})

def compras_lista(request):
    ventas = Venta.objects.filter(usuario=request.user).prefetch_related('items')
    
    for venta in ventas:
        venta.total = sum(item.cantidad * item.precio for item in venta.items.all())

    return render(request, 'venta/compras_lista.html', {'ventas': ventas})

Finder/templates/venta/compra_exitosa.html
{% extends "base.html" %}
{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/venta/compra_exitosa.css' %}">
{% endblock %}

{% block title %}Productos Disponibles{% endblock %}
{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/ventas/compras_lista.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <h1>¡Compra Realizada con Éxito!</h1>
    <p>Tu compra ha sido procesada exitosamente.</p>
    <a href="{% url 'carrito:ver_carrito' %}">Regresar</a>
</div>
{% endblock %}

Finder/templates/venta/compras_lista.html
{% extends "base.html" %}

{% block title %}Mis Compras{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/venta/compras_lista.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>Mis Compras</h1>
    {% for venta in ventas %}
        <div class="venta-block">
            <div class="venta-header">
                <ul class="venta-info">
                    <li><strong>Venta ID:</strong> {{ venta.id }}</li>
                    <li><strong>Fecha:</strong> {{ venta.fecha_venta }}</li>
                    <li><strong>Total:</strong> ${{ venta.total }}</li>
                </ul>
            </div>
            <div class="venta-items">
                <ul>
                    {% for item in venta.items.all %}
                        <li>
                            <span>{{ item.producto.name }}</span> 
                            - Cantidad: {{ item.cantidad }} 
                            - Precio: ${{ item.precio }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
    <a href="{% url 'users:worker_home' %}" class="btn-back">Regresar</a>
</div>
{% endblock %}

Finder/templates/venta/realizar_compra.html
{% extends "base.html" %}
{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/venta/realizar_compra.css' %}">
{% endblock %}

{% block title %}Productos Disponibles{% endblock %}

{% block content %}
<div class="container">
    <h1>De click en aceptar para finalizar la compra</h1>
    <p>Estimado cliente revise sus productos seleccionados.</p>
    <a href="{% url 'carrito:ver_carrito' %}">Aceptar</a>
</div>
{% endblock %}

Finder/templates/venta/ventas_list.html
{% extends "base.html" %}
{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/venta/ventas_list.css' %}">
{% endblock %}
{% block title %}Productos Disponibles{% endblock %}

{% block content %}
<div class="container">
    <h1>Mis Ventas</h1>
    {% for venta in ventas %}
        <h2>Venta ID: {{ venta.id }} - Fecha: {{ venta.fecha_venta }}</h2>
        <ul>
            {% for item in venta.items.all %}
                <li>
                    <span>{{ item.producto.name }}</span> 
                    - Cantidad: {{ item.cantidad }} 
                    - Precio: ${{ item.precio }}
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
    <a href="{% url 'users:empresa_home' %}"class="crear-btn">Regresar</a>
</div>
{% endblock %}