Finder/Finder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from apps.users import views as user_views

app_name = 'finder'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('jobs/', include('apps.jobs.urls')),
    path('materials/', include('apps.materials.urls')),
    path('chat/', include('apps.chat.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('notifications/', include('apps.notifications.urls')),
    path('carrito/', include('apps.carrito.urls')),
    path('venta/', include('apps.venta.urls')),

    path('login/', user_views.login_view, name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('register/', user_views.register_view, name='register'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]
urlpatterns += static( 'media/', document_root  = settings.MEDIA_ROOT )
urlpatterns += static( 'static/', document_root = settings.STATIC_ROOT )

Finder/apps/chat/urls.py
# apps/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('chat_list/', views.chat_list, name='chat_list'),
    path('chat_detail/<int:id>/', views.chat_detail, name='chat_detail'),
]

Finder/apps/jobs/urls.py
# apps/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('create_quotation/<int:service_id>/', views.create_quotation, name='create_quotation'),  # URL para crear un nuevo trabajo
    path('edit_quotation/<int:pk>/', views.edit_quotation, name='edit_quotation'),
    path('list_quotations/', views.list_quotations, name='list_quotations'),
    path('job_list/', views.job_list, name='job_list'),  # URL para crear un nuevo trabajo
    path('quotation_detail/<int:pk>/', views.quotation_detail, name='quotation_detail'),
    path('quotation_detail_empleado/<int:pk>/', views.quotation_detail_empleado, name='quotation_detail_empleado'),
    path('delete_quotation/<int:pk>/', views.delete_quotation, name='delete_quotation'),
    path('finalize_quotation/<int:pk>/', views.finalize_quotation, name='finalize_quotation'),
    path('contraofertar_quotations/<int:pk>/', views.contraofertar_quotations, name='contraofertar_quotations'),
    path('rechazar_quotations/<int:pk>/', views.rechazar_quotations, name='rechazar_quotations'),
    path('aceptar_quotations/<int:pk>/', views.aceptar_quotations, name='aceptar_quotations'),
    path('rechazar_quotations_cliente/<int:pk>/', views.rechazar_quotations_cliente, name='rechazar_quotations_cliente'),
    path('aceptar_quotations_client/<int:pk>/', views.aceptar_quotations_client, name='aceptar_quotations_client'),
    path('leave_review/<int:pk>/', views.leave_review, name='leave_review'),
]

Finder/apps/users/urls.py
# apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('client_home/', views.client_home, name='client_home'),
    path('worker_home/', views.worker_home, name='worker_home'),
    path('empresa_home/', views.empresa_home, name='empresa_home'),
    path('edit_profile/', views.edit_profile_view, name='edit_profile'),
    path('list_services/', views.list_services, name='list_services'),
    path('create_service/', views.create_service, name='create_service'),
    path('edit_service/<int:pk>/', views.edit_service, name='edit_service'),
    path('delete_service/<int:pk>/', views.delete_service, name='delete_service'),
    path('search_services/', views.search_services, name='search_services'),
    path('ver_perfil/<int:pk>/', views.ver_perfil, name='ver_perfil'),

]

Finder/apps/venta/urls.py
# apps/materials/urls.py
from django.urls import path
from . import views

app_name = 'venta'

urlpatterns = [
    path('realizar_compra/', views.realizar_compra, name='realizar_compra'),
    path('compra/exitosa/', views.compra_exitosa, name='compra_exitosa'),
    path('compras_lista/', views.compras_lista, name='compras_lista'),
    path('ventas_list/', views.ventas_list, name='ventas_list'),
]

Finder/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Finder{% endblock %}</title>
    <!-- Agrega aquí estilos globales -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
    {% block style %} 
    <!-- Estilos y librerias -->
    {% endblock %}
</head>
<body>
    <header>
        <div class="header-left">
            <img src="{% static 'images/Finder-LogoHombre.png' %}" alt="Finder Logo" class="logo-img">
        </div>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    {%if user.role == 'trabajador'%}
                     <li><a href="{% url 'users:worker_home' %}">Home</a></li>
                     <li><a href="{% url 'jobs:job_list' %}">Trabajos</a></li>
                     <li><a href="{% url 'users:list_services' %}">Servicios</a></li>
                     <li><a href="{% url 'materials:tienda' %}">Tienda</a></li>
                     <li><a href="{% url 'carrito:ver_carrito' %}">Carrito</a></li>
                     <li><a href="{% url 'venta:compras_lista'%}">Compras</a></li>
                     {% elif user.role == 'cliente' %}
                     <li><a href="{% url 'users:client_home' %}">Home</a></li>
                     <li><a href="{% url 'jobs:list_quotations' %}">Cotizaciones</a></li>

                     {% elif user.role == 'empresa' %}
                     <li><a href="{% url 'users:empresa_home' %}">Home</a></li>
                     <li><a href="{% url 'venta:ventas_list'%}">Ventas</a></li>
                     {% endif %}
                    <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
                    <li><a href="{% url 'notifications:notification_list' %}">Notificaciones</a></li>
                    <li><a href="{% url 'users:profile' %}">Mi Perfil</a></li>
                    <li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        <!-- Contenido dinámico se insertará aquí -->
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2024 Finder. Todos los derechos reservados.</p>
    </footer>
</body>
</html>

Finder/templates/login.html
{% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Finder Login</title>
    <link rel="stylesheet" href="{% static 'css/loginCSS.css' %}">
    </head>
    <body>
        <div class="formulario">
            <div class="logo">
                <img src="{% static 'images/Finder-LogoHombre.png' %}" alt="Logo">
                <h1>Finder</h1>
            </div>
    
            <form method="POST">
                {% csrf_token %}
                <h2>Inicio de Sesión</h2>
                <!-- Campo de correo electrónico -->
                <div class="input-container">
                    <input type="text" id="username" name="username" required>
                    <label for="email">Usuario</label>
                </div>
    
                <!-- Campo de contraseña con funcionalidad de mostrar/ocultar -->
                <div class="input-container">
                    <input type="password" id="password" name="password" required>
                    <label for="password">Contraseña</label>
                    <button type="button" id="togglePassword" class="toggle-password"></button>
                </div>
    
                <div class="recordar">
                    <p><a class="recordar" href="{% url 'password_reset' %}">Olvidé mi contraseña</a></p>
                </div>
                <input type="submit" value="Iniciar sesión">
                <p><a class="recordar" href="{% url 'register' %}">Registrarse</a></p>
            </form>
        </div>
        {% comment %} <script src="loginJs.js"></script> {% endcomment %}
    </body>
    </html> 